name: Input Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment?"
        type: choice
        options:
          - dev
          - staging 
          - prod
          - test
jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show environment
        run: echo "Deploying to ${{ inputs.environment }}"
